#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

$client = new \Phue\Client($_ENV['BRIDGE_IP'], $_ENV['BRIDGE_USER']);
$group = $client->getGroups()[$_ENV['GROUP_ID']];
//$group->setBrightness(0);
//$group->setRGB(0,255,0);
//
//usleep(200000);
//$group->setBrightness(255);
//usleep(200000);
//$group->setBrightness(50);
//usleep(200000);
//$group->setBrightness(255);
//usleep(200000);
//$group->setBrightness(50);
//usleep(200000);
//$group->setBrightness(255);
//usleep(200000);
//$group->setBrightness(50);
//usleep(200000);
//$group->setBrightness(255);
//usleep(200000);
//$group->setBrightness(50);
//usleep(200000);
//$group->setBrightness(255);
var_dump($group);